### ISSUE TITLE
onMeasure这样写有Bug

### ISSUE THREAD

**Issue by mrrobot97** [GcsSloop/arc-seekbar#1]
看了下代码，看到onMeasure时觉得不太对劲，试了一下试出了一个bug。
当measureMode=MeasureSpec.AT_MOST时，不能简单的赋值为default value，还要和当前parent view允许的最大值作比较，取较小的值，不然会出现无法完全绘制的情况。
![screenshot_2018-09-03-10-12-47-125_com gcssloop a](https://user-images.githubusercontent.com/9511542/44964265-12b04d80-af62-11e8-8b05-4341b66af18e.png)

<img width="536" alt="image" src="https://user-images.githubusercontent.com/9511542/44964228-e399dc00-af61-11e8-9726-34de23ea7c23.png">

**Comment by GcsSloop** [comment]
已经处理。

**Comment by GcsSloop** [comment]
谢谢反馈。
